<a href="https://colab.research.google.com/github/jimbounce/Greek_copmuter/blob/main/greek_calc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
# All capitals always count outermost=A,B,C,D = innermost

# Assigning values
A = np.array([1,0,9,0,12,0,6,0,10,0,10,0])
a0 = np.array([12,2,5,10,7,16,8,7,8,8,3,4]) # This line never moves

B = np.array([5,0,10,0,8,0,22,0,16,0,9,0])
b1 = np.array([3,26,6,0,2,13,9,0,17,19,3,12])
b0 = np.array([6,3,3,14,14,21,21,9,9,4,4,6])

C = np.array([4,0,7,15,0,0,14,0,9,0,12,0])
c2 = np.array([21,6,15,4,9,18,11,26,14,1,12,0])
c1 = np.array([9,20,12,3,6,0,14,12,3,8,9,0])
c0 = np.array([7,8,9,10,11,12,13,14,15,4,5,6])

D = np.array([3,0,6,0,10,0,7,0,15,0,8,0])
d3 = np.array([7,3,0,6,0,11,11,6,11,0,6,17])
d2 = np.array([9,13,9,7,13,21,17,4,5,0,7,8])
d1 = np.array([7,0,9,0,7,14,11,0,8,0,16,2])
d0 = np.array([11,14,11,14,14,11,14,11,14,11,11,14])




In [ ]:
# Rotating the A ring
for iA in range(12):
  print("Position", iA+1)
  spinA = np.concatenate((A[iA:], A[:iA]))
  print(spinA)
  # Gaps in A ring
  spinA_gap_indexes= np.nonzero(spinA == 0);    print(spinA_gap_indexes)
  # Using values from under gaps
  for jA in spinA_gap_indexes:_
  spinA[jA] = a0[jA]
  print(spinA,"\n")


    FortyTwo = all([spinA[k]+spinB[k]+spinC[k]+spinD[k] == 42 for k in range(12)])
    if FortyTwo = True:
      print("winA=",spinA, "winB=",spinB, "winC=",spinC, "winD=",spinD)

Position 1
[ 1  0  9  0 12  0  6  0 10  0 10  0]
(array([ 1,  3,  5,  7,  9, 11]),)
[ 1  2  9 10 12 16  6  7 10  8 10  4] 

Position 2
[ 0  9  0 12  0  6  0 10  0 10  0  1]
(array([ 0,  2,  4,  6,  8, 10]),)
[12  9  5 12  7  6  8 10  8 10  3  1] 

Position 3
[ 9  0 12  0  6  0 10  0 10  0  1  0]
(array([ 1,  3,  5,  7,  9, 11]),)
[ 9  2 12 10  6 16 10  7 10  8  1  4] 

Position 4
[ 0 12  0  6  0 10  0 10  0  1  0  9]
(array([ 0,  2,  4,  6,  8, 10]),)
[12 12  5  6  7 10  8 10  8  1  3  9] 

Position 5
[12  0  6  0 10  0 10  0  1  0  9  0]
(array([ 1,  3,  5,  7,  9, 11]),)
[12  2  6 10 10 16 10  7  1  8  9  4] 

Position 6
[ 0  6  0 10  0 10  0  1  0  9  0 12]
(array([ 0,  2,  4,  6,  8, 10]),)
[12  6  5 10  7 10  8  1  8  9  3 12] 

Position 7
[ 6  0 10  0 10  0  1  0  9  0 12  0]
(array([ 1,  3,  5,  7,  9, 11]),)
[ 6  2 10 10 10 16  1  7  9  8 12  4] 

Position 8
[ 0 10  0 10  0  1  0  9  0 12  0  6]
(array([ 0,  2,  4,  6,  8, 10]),)
[12 10  5 10  7  1  8  9  8 12  3  6] 

Position

(array([ 1,  3,  5,  7,  9, 11]),)
[ 1  2  9 10 12 16  6  7 10  8 10  4]
