<a href="https://colab.research.google.com/github/jimbounce/Greek_copmuter/blob/main/greek_calc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
# All capitals always count outermost=A,B,C,D = innermost

# Assigning values
A = np.array([1,0,9,0,12,0,6,0,10,0,10,0])
a0 = np.array([12,2,5,10,7,16,8,7,8,8,3,4]) # This line never moves

B = np.array([5,0,10,0,8,0,22,0,16,0,9,0])
b1 = np.array([3,26,6,0,2,13,9,0,17,19,3,12])
b0 = np.array([6,3,3,14,14,21,21,9,9,4,4,6]) # This line never moves

C = np.array([4,0,7,15,0,0,14,0,9,0,12,0])
c2 = np.array([21,6,15,4,9,18,11,26,14,1,12,0])
c1 = np.array([9,20,12,3,6,0,14,12,3,8,9,0])
c0 = np.array([7,8,9,10,11,12,13,14,15,4,5,6]) # This line never moves

D = np.array([3,0,6,0,10,0,7,0,15,0,8,0])
d3 = np.array([7,3,0,6,0,11,11,6,11,0,6,17])
d2 = np.array([9,13,9,7,13,21,17,4,5,0,7,8])
d1 = np.array([7,0,9,0,7,14,11,0,8,0,16,2])
d0 = np.array([11,14,11,14,14,11,14,11,14,11,11,14]) # This line never moves

In [12]:
# same ring dependancies
# A spins w. b1, c1, d1
# B spins w.
# C
# D spin

for i in range(12):
  A = np.roll(A, 1)
  a0 = np.roll(a0, 1)
  B = np.roll(B, 1)
  b1 = np.roll(b1, 1)
  b0 = np.roll(b0, 1)
  C = np.roll(C, 1)
  c2 = np.roll(c2, 1)
  c1 = np.roll(c1, 1)
  c0 = np.roll(c0, 1)
  D = np.roll(D, 1)
  d3 = np.roll(d3, 1)
  d2 = np.roll(d2, 1)
  d1 = np.roll(d1, 1)
  d0 = np.roll(d0, 1)

  print(c2)

        # Replacing A,B,C,D gaps
        for m in range(len(D)):
          if D[m]!=0:
              break
          elif D[m]==0 and d3[m]!=0:
            D[m] = d3[m]
            break
          elif D[m]==0 and d3[m]==0 and d2[m]!=0:
            D[m] = d2[m]
            break
          elif D[m]==0 and d3[m]==0 and d2[m]==0 and d1[m]!=0:
            D[m] = d1[m]
            break
          else:
            D[m] = d0[m]

        for n in range(len(C)):
          if C[n]!=0:
            break
          elif C[n]==0 and c2[n]!=0:
            C[n] = c2[n]
            break
          elif C[n]==0 and c2[n]==0 and c1[n]!=0:
            C[n] = c1[n]
            break
          else:
            C[n] = c0[n]

        for p in range(len(B)):
          if B[p]!=0:
            break
          elif B[p] == 0 and b1[p]!=0:
            B[p] = b1[p]
            break
          elif B[p]==0 and b1[p]==0:
              B[p] = b0[p]

        for q in range(len(A)):
          if A[q]!=0:
            break
          elif A[q] == 0:
            A[q] = a0[q]

        s0=A[0]+B[0]+C[0]+D[0]
        s1=A[1]+B[1]+C[1]+D[1]
        s2=A[2]+B[2]+C[2]+D[2]
        s3=A[3]+B[3]+C[3]+D[3]
        s4=A[4]+B[4]+C[4]+D[4]
        s5=A[5]+B[5]+C[5]+D[5]
        s6=A[6]+B[6]+C[6]+D[6]
        s7=A[7]+B[7]+C[7]+D[7]
        s8=A[8]+B[8]+C[8]+D[8]
        s9= A[9]+B[9]+C[9]+D[9]
        s10=A[10]+B[10]+C[10]+D[10]
        s11=A[11]+B[11]+C[11]+D[11]

        if s0==s1==s2==s3==s4==s5==s6==s7==s8==s9==s10==s11==42:
          print("all are 42", A, B, C, D)
          break

print(count)

#   print("sum ", A[0]+B[0]+C[0]+D[0])
# FortyTwo = all([A[k]+B[k]+C[k]+D[k] == 42 for k in range(12)])
# if FortyTwo == True:
    #   print("Yes")
    #   # print("winA=",A[:3], "winB=",B[:2], "winC=",C[:2], "winD=",D[:2])

[ 0 21  6 15  4  9 18 11 26 14  1 12]
[12  0 21  6 15  4  9 18 11 26 14  1]
[ 1 12  0 21  6 15  4  9 18 11 26 14]
[14  1 12  0 21  6 15  4  9 18 11 26]
[26 14  1 12  0 21  6 15  4  9 18 11]
[11 26 14  1 12  0 21  6 15  4  9 18]
[18 11 26 14  1 12  0 21  6 15  4  9]
[ 9 18 11 26 14  1 12  0 21  6 15  4]
[ 4  9 18 11 26 14  1 12  0 21  6 15]
[15  4  9 18 11 26 14  1 12  0 21  6]
[ 6 15  4  9 18 11 26 14  1 12  0 21]
[21  6 15  4  9 18 11 26 14  1 12  0]
